name: Run the Robot Framework tests

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "develop"
      - "main"

jobs:
  Tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: nl-kat-rocky

      - name: Inject slug/short variables for branch names
        uses: rlespinasse/github-slug-action@v4

      - name: Download and run grcr containers
        run: docker-compose -f .ci/docker-compose-robot-coordination.yml up -d
        working-directory: nl-kat-rocky
        env:
          KAT_VERSION: ${{ env.GITHUB_REF_NAME_SLUG }}

      - name: Seed katalogus boefjes
        run: docker-compose -f .ci/docker-compose-robot-coordination.yml exec katalogus python3 -m boefjes.seed

      - name: Seed rocky
        run: docker-compose -f .ci/docker-compose-robot-coordination.yml exec rocky python3 manage.py loaddata OOI_database_seed.json

      - name: Create superuser
        run: docker-compose -f .ci/docker-compose-robot-coordination.yml exec rocky python3 manage.py createsuperuser

      - name: Setup dev account
        run: docker-compose -f .ci/docker-compose-robot-coordination.yml exec rocky python3 manage.py setup_dev_account
